GET http://localhost:3001/books HTTP/1.1
Content-Type: application/json

### 
POST http://localhost:3001/books HTTP/1.1
Content-Type: application/json

{
    "title": "Sonic Adventure"
}

### 
PUT http://localhost:3001/books/1 HTTP/1.1
Content-Type: application/json

{
    "title": "Harry Potter & The Sorcerer Stone"
}

### 
DELETE http://localhost:3001/books/1 HTTP/1.1
Content-Type: application/json